### ISSUE TITLE
Pip versions > 10 are not supported

### ISSUE THREAD

**Issue by kevinkjt2000** [darvid/reqwire#18]
I get the stacktrace below if I use any pip > 10
```
$ reqwire build -a
Traceback (most recent call last):
  File "/home/kevin/.local/bin/reqwire", line 7, in <module>
    from reqwire.cli import main
  File "/home/kevin/.local/lib/python3.7/site-packages/reqwire/cli.py", line 16, in <module>
    import reqwire.helpers.requirements
  File "/home/kevin/.local/lib/python3.7/site-packages/reqwire/helpers/requirements.py", line 15, in <module>
    import pip.basecommand
ModuleNotFoundError: No module named 'pip.basecommand'
```

Current workaround is to downgrade back to pip < 10, e.g.:
```
pip install -U "pip<10"
```
Reqwire version 0.2.1

**Comment by darvid** [comment]
Hey, I'll look into this when I get a free moment, but I initially wrote reqwire as a stopgap, awaiting tools like [pipenv](https://pipenv.readthedocs.io/en/latest/) and [poetry](https://github.com/sdispater/poetry) that support the Pipfile spec to come out. Now that those tools are out and fairly mature, I'd suggest taking a look and seeing which one fits your workflow best and using it over reqwire.

**Comment by kevinkjt2000** [comment]
pipenv cannot manage multiple groupings of dependencies for multiple versions of python as easily as this tool can.  I have not yet looked at poetry, and woooow does it look promising!  I'll have to give that a try at some point, and hope it works well with tox.
